function result = analyze_moving_bar_stimulus(base_Stimuli, base_dff, base_TimeCa, ...
        drug_Stimuli, drug_dff, drug_TimeCa, base_match_idx_local, drug_match_idx_local, matched_rois_available)
    result = analyze_direction_stimulus('moving_bar', 'bar_orientations', ...
        base_Stimuli, base_dff, base_TimeCa, drug_Stimuli, drug_dff, drug_TimeCa, ...
        base_match_idx_local, drug_match_idx_local, matched_rois_available);
end
